/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangCheckSignCombinationsRouteImport } from './routes/$lang.check-sign-combinations'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangSignsRouteImport } from './routes/$lang.signs'
import { Route as LangTaginfoRouteImport } from './routes/$lang.taginfo'
import { Route as LangWikiRouteImport } from './routes/$lang.wiki'
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangWikiRoute = LangWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => LangRoute,
} as any)
const LangTaginfoRoute = LangTaginfoRouteImport.update({
  id: '/taginfo',
  path: '/taginfo',
  getParentRoute: () => LangRoute,
} as any)
const LangSignsRoute = LangSignsRouteImport.update({
  id: '/signs',
  path: '/signs',
  getParentRoute: () => LangRoute,
} as any)
const LangCheckSignCombinationsRoute = LangCheckSignCombinationsRouteImport.update({
  id: '/check-sign-combinations',
  path: '/check-sign-combinations',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/check-sign-combinations': typeof LangCheckSignCombinationsRoute
  '/$lang/signs': typeof LangSignsRoute
  '/$lang/taginfo': typeof LangTaginfoRoute
  '/$lang/wiki': typeof LangWikiRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/check-sign-combinations': typeof LangCheckSignCombinationsRoute
  '/$lang/signs': typeof LangSignsRoute
  '/$lang/taginfo': typeof LangTaginfoRoute
  '/$lang/wiki': typeof LangWikiRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/check-sign-combinations': typeof LangCheckSignCombinationsRoute
  '/$lang/signs': typeof LangSignsRoute
  '/$lang/taginfo': typeof LangTaginfoRoute
  '/$lang/wiki': typeof LangWikiRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/check-sign-combinations'
    | '/$lang/signs'
    | '/$lang/taginfo'
    | '/$lang/wiki'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/check-sign-combinations'
    | '/$lang/signs'
    | '/$lang/taginfo'
    | '/$lang/wiki'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/check-sign-combinations'
    | '/$lang/signs'
    | '/$lang/taginfo'
    | '/$lang/wiki'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/wiki': {
      id: '/$lang/wiki'
      path: '/wiki'
      fullPath: '/$lang/wiki'
      preLoaderRoute: typeof LangWikiRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/taginfo': {
      id: '/$lang/taginfo'
      path: '/taginfo'
      fullPath: '/$lang/taginfo'
      preLoaderRoute: typeof LangTaginfoRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/signs': {
      id: '/$lang/signs'
      path: '/signs'
      fullPath: '/$lang/signs'
      preLoaderRoute: typeof LangSignsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/check-sign-combinations': {
      id: '/$lang/check-sign-combinations'
      path: '/check-sign-combinations'
      fullPath: '/$lang/check-sign-combinations'
      preLoaderRoute: typeof LangCheckSignCombinationsRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangCheckSignCombinationsRoute: typeof LangCheckSignCombinationsRoute
  LangSignsRoute: typeof LangSignsRoute
  LangTaginfoRoute: typeof LangTaginfoRoute
  LangWikiRoute: typeof LangWikiRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangCheckSignCombinationsRoute: LangCheckSignCombinationsRoute,
  LangSignsRoute: LangSignsRoute,
  LangTaginfoRoute: LangTaginfoRoute,
  LangWikiRoute: LangWikiRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
