/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DERouteImport } from './routes/DE'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DEIndexRouteImport } from './routes/DE.index'
import { Route as DEWikiRouteImport } from './routes/DE.wiki'
import { Route as DETaginfoRouteImport } from './routes/DE.taginfo'
import { Route as DESignsRouteImport } from './routes/DE.signs'
import { Route as DECheckSignCombinationsRouteImport } from './routes/DE.check-sign-combinations'

const DERoute = DERouteImport.update({
  id: '/DE',
  path: '/DE',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DEIndexRoute = DEIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DERoute,
} as any)
const DEWikiRoute = DEWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => DERoute,
} as any)
const DETaginfoRoute = DETaginfoRouteImport.update({
  id: '/taginfo',
  path: '/taginfo',
  getParentRoute: () => DERoute,
} as any)
const DESignsRoute = DESignsRouteImport.update({
  id: '/signs',
  path: '/signs',
  getParentRoute: () => DERoute,
} as any)
const DECheckSignCombinationsRoute = DECheckSignCombinationsRouteImport.update({
  id: '/check-sign-combinations',
  path: '/check-sign-combinations',
  getParentRoute: () => DERoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/DE': typeof DERouteWithChildren
  '/DE/check-sign-combinations': typeof DECheckSignCombinationsRoute
  '/DE/signs': typeof DESignsRoute
  '/DE/taginfo': typeof DETaginfoRoute
  '/DE/wiki': typeof DEWikiRoute
  '/DE/': typeof DEIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/DE/check-sign-combinations': typeof DECheckSignCombinationsRoute
  '/DE/signs': typeof DESignsRoute
  '/DE/taginfo': typeof DETaginfoRoute
  '/DE/wiki': typeof DEWikiRoute
  '/DE': typeof DEIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/DE': typeof DERouteWithChildren
  '/DE/check-sign-combinations': typeof DECheckSignCombinationsRoute
  '/DE/signs': typeof DESignsRoute
  '/DE/taginfo': typeof DETaginfoRoute
  '/DE/wiki': typeof DEWikiRoute
  '/DE/': typeof DEIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/DE'
    | '/DE/check-sign-combinations'
    | '/DE/signs'
    | '/DE/taginfo'
    | '/DE/wiki'
    | '/DE/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/DE/check-sign-combinations'
    | '/DE/signs'
    | '/DE/taginfo'
    | '/DE/wiki'
    | '/DE'
  id:
    | '__root__'
    | '/'
    | '/DE'
    | '/DE/check-sign-combinations'
    | '/DE/signs'
    | '/DE/taginfo'
    | '/DE/wiki'
    | '/DE/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DERoute: typeof DERouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/DE': {
      id: '/DE'
      path: '/DE'
      fullPath: '/DE'
      preLoaderRoute: typeof DERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DE/': {
      id: '/DE/'
      path: '/'
      fullPath: '/DE/'
      preLoaderRoute: typeof DEIndexRouteImport
      parentRoute: typeof DERoute
    }
    '/DE/wiki': {
      id: '/DE/wiki'
      path: '/wiki'
      fullPath: '/DE/wiki'
      preLoaderRoute: typeof DEWikiRouteImport
      parentRoute: typeof DERoute
    }
    '/DE/taginfo': {
      id: '/DE/taginfo'
      path: '/taginfo'
      fullPath: '/DE/taginfo'
      preLoaderRoute: typeof DETaginfoRouteImport
      parentRoute: typeof DERoute
    }
    '/DE/signs': {
      id: '/DE/signs'
      path: '/signs'
      fullPath: '/DE/signs'
      preLoaderRoute: typeof DESignsRouteImport
      parentRoute: typeof DERoute
    }
    '/DE/check-sign-combinations': {
      id: '/DE/check-sign-combinations'
      path: '/check-sign-combinations'
      fullPath: '/DE/check-sign-combinations'
      preLoaderRoute: typeof DECheckSignCombinationsRouteImport
      parentRoute: typeof DERoute
    }
  }
}

interface DERouteChildren {
  DECheckSignCombinationsRoute: typeof DECheckSignCombinationsRoute
  DESignsRoute: typeof DESignsRoute
  DETaginfoRoute: typeof DETaginfoRoute
  DEWikiRoute: typeof DEWikiRoute
  DEIndexRoute: typeof DEIndexRoute
}

const DERouteChildren: DERouteChildren = {
  DECheckSignCombinationsRoute: DECheckSignCombinationsRoute,
  DESignsRoute: DESignsRoute,
  DETaginfoRoute: DETaginfoRoute,
  DEWikiRoute: DEWikiRoute,
  DEIndexRoute: DEIndexRoute,
}

const DERouteWithChildren = DERoute._addFileChildren(DERouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DERoute: DERouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
