export * as SvgsDE from './DE/index.js'
export { SvgLoadersDE } from './DE/loaders.js'
export * as SvgsBE from './BE/index.js'
export { SvgLoadersBE } from './BE/loaders.js'
export * as SvgsAT from './AT/index.js'
export { SvgLoadersAT } from './AT/loaders.js'
