/**
 * Generate the checked-in registry artifacts from the YAML source of truth:
 *   src/data/registry.json          — combined
 *   src/data/registry_<CC>.json     — per country
 *   src/data/REGISTRY.md            — human-readable coverage report ("where the errors are")
 *
 * Output is deterministic (no timestamps) so `git status` stays clean between runs.
 * Run: `bun run registry:generate`
 */
import { resolve } from 'node:path'
import type { CountryRegistry, RegistryStatus, SpriteRegistryEntry } from '../src/registry/types.ts'
import { buildRegistry } from './buildRegistry.ts'

const DATA_DIR = resolve(import.meta.dir, '../src/data')

const STATUS_LABEL: Record<RegistryStatus, string> = {
  ok: '✅ ok (in a sprite)',
  'svg-missing': '🟡 svg-missing (signId in catalogue, no SVG yet)',
  'signId-not-in-tool': '🟠 signId-not-in-tool (not in the country catalogue)',
  'country-not-in-tool': '⛔ country-not-in-tool (no catalogue in this tool yet)',
}

function errorList(entries: SpriteRegistryEntry[], status: RegistryStatus): string {
  const rows = entries.filter((e) => e.status === status)
  if (rows.length === 0) return '_none_'
  return rows.map((e) => `\`${e.osmValue}\` (${e.yolo})`).join(', ')
}

function renderMarkdown(byCountry: CountryRegistry[]): string {
  const lines: string[] = []
  lines.push('# Panoramax sprite registry — coverage report')
  lines.push('')
  lines.push(
    '> Generated by `bun run registry:generate` from `src/registry/panoramax-classes.yaml`. Do not edit by hand.',
  )
  lines.push('')
  lines.push(
    'This maps every Panoramax traffic-sign detection class to this tool’s catalogue and shows exactly where the gaps are. Only `ok` entries end up in a generated sprite sheet.',
  )
  lines.push('')
  lines.push('## Summary')
  lines.push('')
  lines.push(
    '| Country | Catalogue in tool? | Classes | ✅ ok | 🟡 svg-missing | 🟠 signId-not-in-tool | ⛔ country-not-in-tool |',
  )
  lines.push('| --- | --- | --: | --: | --: | --: | --: |')
  for (const c of byCountry) {
    const total = c.entries.length
    lines.push(
      `| ${c.country} | ${c.hasCatalogue ? 'yes' : 'no'} | ${total} | ${c.counts.ok} | ${c.counts['svg-missing']} | ${c.counts['signId-not-in-tool']} | ${c.counts['country-not-in-tool']} |`,
    )
  }
  lines.push('')
  for (const c of byCountry) {
    lines.push(`## ${c.country}`)
    lines.push('')
    if (!c.hasCatalogue) {
      lines.push(
        `No catalogue for **${c.country}** in this tool yet — all ${c.entries.length} classes are stored as prepared data (\`country-not-in-tool\`). Add the catalogue + SVGs upstream and re-run to light them up.`,
      )
      lines.push('')
      continue
    }
    for (const status of ['svg-missing', 'signId-not-in-tool'] as const) {
      const count = c.counts[status]
      lines.push(`### ${STATUS_LABEL[status]} — ${count}`)
      lines.push('')
      lines.push(errorList(c.entries, status))
      lines.push('')
    }
  }
  return `${lines.join('\n')}\n`
}

const { byCountry, all } = await buildRegistry()

await Bun.write(
  resolve(DATA_DIR, 'registry.json'),
  `${JSON.stringify({ countries: byCountry }, null, 2)}\n`,
)
for (const country of byCountry) {
  await Bun.write(
    resolve(DATA_DIR, `registry_${country.country}.json`),
    `${JSON.stringify(country, null, 2)}\n`,
  )
}
await Bun.write(resolve(DATA_DIR, 'REGISTRY.md'), renderMarkdown(byCountry))

const okTotal = all.filter((e) => e.status === 'ok').length
console.log(`Registry: ${all.length} classes across ${byCountry.length} countries, ${okTotal} ok.`)
for (const c of byCountry) {
  console.log(
    `  ${c.country}: ok=${c.counts.ok} svg-missing=${c.counts['svg-missing']} signId-not-in-tool=${c.counts['signId-not-in-tool']} country-not-in-tool=${c.counts['country-not-in-tool']}`,
  )
}
